#!/usr/bin/env bash
if grep -q ":" <<< "$1"; then
	read -r user group <<< "$(tr ":" " " <<< "$1")"
	shift
else
	user="$1"
	group="$2"
	shift 2
fi

for i in /dev/std*; do
	chmod a+w "$i"
done
exec runuser -u "$user" -g "$group" "$@"
